site_name: DEWCBoKS
site_url: https://dewcservices.github.io/
theme:
  name: material
extra_css:
- assets/extra.css
extra_javascript:
- assets/extra.js
plugins:
- search
- open-in-new-tab
#- tags:
#    tags_file: tags.md
