site_name: DEWCBoKS Cyber
site_url: https://dewcservices.github.io/
theme:
  name: material
  features:
    - search.suggest
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js
plugins:
  - search
  - open-in-new-tab
#- tags:
#    tags_file: tags.md
